import type { SourceAdapter, RawDealItem } from './source-adapter.js';
import { format } from 'date-fns';

const WEEK_START = format(new Date(), 'yyyy-MM-dd');

const MOCK_DEALS: RawDealItem[] = [
  {
    store_id: 'superc-joliette',
    store_name: 'Super C Joliette',
    item_name: 'Poitrine de poulet sans os',
    normalized_name: 'poitrine de poulet',
    category: 'viande',
    current_price: 4.99,
    source_system: 'mock',
    source_type: 'mock',
    size: '1',
    unit: 'kg',
    confidence: 'HIGH',
    week_start: WEEK_START,
    notes: 'Spécial de la semaine'
  },
  {
    store_id: 'maxi-joliette',
    store_name: 'Maxi Joliette',
    item_name: 'Beurre Lactantia 454g',
    normalized_name: 'beurre',
    brand: 'Lactantia',
    category: 'produits-laitiers',
    current_price: 4.88,
    source_system: 'mock',
    source_type: 'mock',
    size: '454',
    unit: 'g',
    confidence: 'HIGH',
    week_start: WEEK_START,
  },
  {
    store_id: 'metro-joliette',
    store_name: 'Metro Joliette',
    item_name: 'Fromage cheddar fort 400g',
    normalized_name: 'fromage cheddar',
    brand: 'Cracker Barrel',
    category: 'produits-laitiers',
    current_price: 3.99,
    source_system: 'mock',
    source_type: 'mock',
    size: '400',
    unit: 'g',
    confidence: 'HIGH',
    week_start: WEEK_START,
    notes: 'Spécial'
  },
  {
    store_id: 'iga-joliette',
    store_name: 'IGA Joliette',
    item_name: 'Raisins rouges sans pépins',
    normalized_name: 'raisins',
    category: 'fruits',
    current_price: 3.49,
    source_system: 'mock',
    source_type: 'mock',
    size: '1',
    unit: 'kg',
    confidence: 'HIGH',
    week_start: WEEK_START,
  },
  {
    store_id: 'superc-joliette',
    store_name: 'Super C Joliette',
    item_name: 'Boeuf haché extra maigre',
    normalized_name: 'boeuf hache',
    category: 'viande',
    current_price: 5.49,
    source_system: 'mock',
    source_type: 'mock',
    size: '1',
    unit: 'kg',
    confidence: 'HIGH',
    week_start: WEEK_START,
  },
  {
    store_id: 'bonichoix-stemilie',
    store_name: "BoniChoix St-Émilie-de-l'Énergie",
    item_name: 'Côtelettes de porc',
    normalized_name: 'cotes de porc',
    category: 'viande',
    current_price: 3.99,
    source_system: 'mock',
    source_type: 'mock',
    size: '1',
    unit: 'kg',
    confidence: 'MEDIUM',
    week_start: WEEK_START,
  },
  {
    store_id: 'maxi-joliette',
    store_name: 'Maxi Joliette',
    item_name: 'Fraises fraîches 1lb',
    normalized_name: 'fraises',
    category: 'fruits',
    current_price: 2.49,
    source_system: 'mock',
    source_type: 'mock',
    size: '454',
    unit: 'g',
    confidence: 'HIGH',
    week_start: WEEK_START,
    notes: 'Saison des fraises'
  },
  {
    store_id: 'metro-joliette',
    store_name: 'Metro Joliette',
    item_name: 'Saumon atlantique filet',
    normalized_name: 'saumon',
    category: 'poisson',
    current_price: 9.99,
    source_system: 'mock',
    source_type: 'mock',
    size: '1',
    unit: 'kg',
    confidence: 'HIGH',
    week_start: WEEK_START,
  },
  {
    store_id: 'iga-joliette',
    store_name: 'IGA Joliette',
    item_name: 'Café Van Houtte 930g',
    normalized_name: 'cafe',
    brand: 'Van Houtte',
    category: 'epicerie',
    current_price: 12.99,
    source_system: 'mock',
    source_type: 'mock',
    size: '930',
    unit: 'g',
    confidence: 'HIGH',
    week_start: WEEK_START,
    notes: 'Prix régulier'
  },
  {
    store_id: 'superc-joliette',
    store_name: 'Super C Joliette',
    item_name: 'Légumes surgelés mélangés 1kg',
    normalized_name: 'legumes surgeles',
    category: 'congeles',
    current_price: 2.49,
    source_system: 'mock',
    source_type: 'mock',
    size: '1000',
    unit: 'g',
    confidence: 'HIGH',
    week_start: WEEK_START,
  },
  {
    store_id: 'maxi-joliette',
    store_name: 'Maxi Joliette',
    item_name: 'Pommes de terre jaunes 10lb',
    normalized_name: 'pommes de terre',
    category: 'legumes',
    current_price: 4.99,
    source_system: 'mock',
    source_type: 'mock',
    size: '4536',
    unit: 'g',
    confidence: 'HIGH',
    week_start: WEEK_START,
  },
  {
    store_id: 'metro-joliette',
    store_name: 'Metro Joliette',
    item_name: 'Pâtes spaghetti Barilla 900g',
    normalized_name: 'pates',
    brand: 'Barilla',
    category: 'epicerie',
    current_price: 2.49,
    source_system: 'mock',
    source_type: 'mock',
    size: '900',
    unit: 'g',
    confidence: 'HIGH',
    week_start: WEEK_START,
    notes: '2 pour 5$'
  },
  {
    store_id: 'iga-joliette',
    store_name: 'IGA Joliette',
    item_name: 'Oeufs blancs extra larges 12',
    normalized_name: 'oeufs',
    category: 'produits-laitiers',
    current_price: 5.49,
    source_system: 'mock',
    source_type: 'mock',
    size: '12',
    unit: 'each',
    confidence: 'HIGH',
    week_start: WEEK_START,
    notes: 'Prix habituel'
  },
];

export class MockAdapter implements SourceAdapter {
  id = 'mock';
  store_id = 'all';
  enabled = true;

  async collect(): Promise<RawDealItem[]> {
    return MOCK_DEALS;
  }
}
